# Generated by Django 5.1.1 on 2025-06-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('correo_personal', models.EmailField(max_length=254)),
                ('correo_inacap', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
